### ISSUE TITLE
Opener not showing up

### ISSUE THREAD

**Issue by bk231** [ebaauw/homebridge-nb#100]
Hi! Thanks so much for all your amazing work! Really enjoying a number of your plugins.

I have a Nuki Opener and Lock (1st Gen)

I have enabled the nuki bridge HTTP API through the app, and have taken what I thought were the correct steps to ensure the plugin to function. The Nuki lock does appear and work well, but there is no sign of the Opener. Log shows that unsuccessful at requesting something, and tries to one time per minute with the following error:

14:01:41" (from "Tue Apr 04 2023 14:00:41")
[04/04/2023, 14:01:41] [Nuki] Nuki_Bridge_17D831E1: warning: heartbeat error: RangeError: : invalid name
    at Opener.set name [as name] (/var/lib/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:132:13)
    at new Delegate (/var/lib/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:39:15)
    at new AccessoryDelegate (/var/lib/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/AccessoryDelegate.js:43:5)
    at new NbAccessory (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:14:5)
    at new Opener (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:373:5)
    at Bridge.addOpener (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:218:24)
    at Bridge.heartbeat (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:279:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

As I am not so experienced on here, could you possibly locate what the source of the problem might be?

Thanks so much for your help! Been enjoying being a new HomeBridge user:)

**Comment by bk231** [comment]
It didn't have a name, you were right, upon checking nb list and the Nuki app. So I added a name on the app, which is now saved there. Restarted homebridge but it still doesn't show up on nb list. How do I had the name there? Should I uninstall and reinstall?

**Comment by ebaauw** [comment]
Does the name now show on `nb list`?  If so, Homebridge NB should pick it up, or try restarting Homebridge.  If not, try power cycling the Nuki bridge, and check again.

**Comment by bk231** [comment]
The name finally showed up on nb list. A subsequent restart did the trick. Thank you!
