### ISSUE TITLE
opener is not displayed in Homebridge, only the Bridge

### ISSUE THREAD

**Issue by lindnbe** [ebaauw/homebridge-nb#117]
I am trying to get my Nuki Opener in to Homebrdige, but I am getting only the below error message.
Maybe someone could help me with that. Many thanks in advance.

[24/07/2023, 11:11:16] [Nuki] hardware: Raspberry Pi 3B+ 1.3 (1GB)
[24/07/2023, 11:11:16] [Nuki] os: Raspbian GNU/Linux 11 (bullseye) [32 bit]
[24/07/2023, 11:11:19] [Nuki] Bridge_26D0A987: press Nuki bridge button to obtain token
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: logLevel: set to 2
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Name: set to "Nuki_Bridge_26D0A987"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Serial Number: set to "26D0A987"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Model: set to "Bridge"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Firmware Revision: set to "2.15.0"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Nuki Bridge v2.15.0 26D0A987 at 10.10.20.252:8080
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Name: set to "Nuki_Bridge_26D0A987"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Configured Name: set to "Nuki_Bridge_26D0A987"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Heartrate: set to 60 seconds
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Restart: set to false
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Log Level: set to 2
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Status Fault: set to 0
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Name: set to "Nuki_Bridge_26D0A987"
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: Configured Name: set to "Nuki_Bridge_26D0A987"
[24/07/2023, 11:11:33] [Nuki] listening on http://0.0.0.0:35289/notify
[24/07/2023, 11:11:33] [Nuki] Nuki_Bridge_26D0A987: subscribe to event notifications
[24/07/2023, 11:11:35] [Nuki] Nuki_Bridge_26D0A987: Last Updated: set to "Mon Jul 24 2023 11:11:39"
[24/07/2023, 11:11:35] [Nuki] Nuki_Bridge_26D0A987: Last Boot: set to "Thu Mar 02 2023 09:54:58"
[24/07/2023, 11:11:35] [Nuki] Nuki_Bridge_26D0A987: warning: heartbeat error: RangeError: : invalid name
    at Opener.set name [as name] (/var/lib/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:132:13)
    at new Delegate (/var/lib/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:39:15)
    at new AccessoryDelegate (/var/lib/homebridge/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/AccessoryDelegate.js:43:5)
    at new NbAccessory (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:14:5)
    at new Opener (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:407:5)
    at Bridge.addOpener (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:230:24)
    at Bridge.heartbeat (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:287:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Bridge.init (/var/lib/homebridge/node_modules/homebridge-nb/lib/NbAccessory.js:172:7)

**Comment by ebaauw** [comment]
Did you set a name for the Opener in the Nuki app?

**Comment by lindnbe** [comment]
Yes, there is a Name configured for the opener "Haustuer". I tested also another Name but still the same issue.

**Comment by lindnbe** [comment]
After Name change and bridge reboot is the system finally online. Many thanks!
