### ISSUE TITLE
Opener not detected

### ISSUE THREAD

**Issue by YTKengo** [ebaauw/homebridge-nb#118]
Hello,

I installed the plugin, that worked very well. The problem now is, that my Nuki Opener is not detected by the plugin. The opener is connected with the bridge and is working totaly fine, but the plugin does not recognize it.

Best wishes
Kengo

**Comment by ebaauw** [comment]
Please attach the Homebridge log file.  Also, please list the output of `nb list`.

**Comment by Domenikus** [comment]
Same issue here

[Nuki] Nuki_Bridge_28AB2C52: warning: heartbeat error: RangeError: : invalid name
    at Opener.set name [as name] (/usr/local/lib/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:132:13)
    at new Delegate (/usr/local/lib/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/Delegate.js:39:15)
    at new AccessoryDelegate (/usr/local/lib/node_modules/homebridge-nb/node_modules/homebridge-lib/lib/AccessoryDelegate.js:43:5)
    at new NbAccessory (/usr/local/lib/node_modules/homebridge-nb/lib/NbAccessory.js:14:5)
    at new Opener (/usr/local/lib/node_modules/homebridge-nb/lib/NbAccessory.js:407:5)
    at Bridge.addOpener (/usr/local/lib/node_modules/homebridge-nb/lib/NbAccessory.js:230:24)
    at Bridge.heartbeat (/usr/local/lib/node_modules/homebridge-nb/lib/NbAccessory.js:287:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ebaauw** [comment]
Make sure to assign a name to the opener in the Nuki app, and power-cycle the Nuki bridge so it picks up that name.

**Comment by YTKengo** [comment]
Thanks. That solved the problem for meAm 27.07.2023 um 23:48 schrieb Erik Baauw ***@***.***>:﻿
Make sure to assign a name to the opener in the Nuki app, and power-cycle the Nuki bridge so it picks up that name.

**Comment by Domenikus** [comment]
Also fixed on my side. Thank you
