### ISSUE TITLE
Latest NB update gives log warning --> TypeError: this[("add" + className)]

### ISSUE THREAD

**Issue by mtressl** [ebaauw/homebridge-nb#142]
The latest update (v1.4.24) shows repeatedly the following waring in my logs:

`[9/20/2024, 5:05:49 PM] [homebridge-nb] warning: TypeError: this[("add" + className)] is not a function
    at NbPlatform.foundBridge (file:///var/lib/homebridge/node_modules/homebridge-nb/lib/NbPlatform.js:253:40)
    at NbPlatform.discover (file:///var/lib/homebridge/node_modules/homebridge-nb/lib/NbPlatform.js:143:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NbPlatform.heartbeat (file:///var/lib/homebridge/node_modules/homebridge-nb/lib/NbPlatform.js:159:9)
[9/20/2024, 5:05:49 PM] [homebridge-nb] warning: TypeError: this[("add" + className)] is not a function
    at NbPlatform.foundBridge (file:///var/lib/homebridge/node_modules/homebridge-nb/lib/NbPlatform.js:253:40)
    at NbPlatform.discover (file:///var/lib/homebridge/node_modules/homebridge-nb/lib/NbPlatform.js:143:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NbPlatform.heartbeat (file:///var/lib/homebridge/node_modules/homebridge-nb/lib/NbPlatform.js:159:9)`

Everything seems to work fine, just wanted to point it out.

**Comment by ebaauw** [comment]
Fixed in v1.4.25.

**Comment by ebaauw** [comment]
v1.4.25 also has issues, see #143.  Best revert to v1.4.23 for now.
