### ISSUE TITLE
Heartbeat Error - TypeError: Cannot read properties of undefined (reading 'ringactionTimestamp')

### ISSUE THREAD

**Issue by floriangrotz** [ebaauw/homebridge-nb#67]
Error in Log

[07/05/2022, 13:02:27] [Nuki] Nuki_Bridge_xxxxxxxx: warning: heartbeat error: TypeError: Cannot read properties of undefined (reading 'ringactionTimestamp')
    at DoorBell.update (/usr/local/lib/node_modules/homebridge-nb/lib/NbService.js:360:15)
    at Opener.update (/usr/local/lib/node_modules/homebridge-nb/lib/NbAccessory.js:371:26)
    at Bridge.heartbeat (/usr/local/lib/node_modules/homebridge-nb/lib/NbAccessory.js:281:32)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by floriangrotz** [comment]
I had an Opener who was offline.
As improvement it could be took under consideration that a Lock / Opener has no Bluetooth connection.

**Comment by ebaauw** [comment]
Afaik, the Nuki bridge API doesn’t provide any info on the Bluetooth connection between the bridge and the Nuki device.  It returns the cached device state without actually checking the connection, which is a good thing, or the device battery would be drained too quickly.

It would seem, in your case, the Nuki bridge didn’t include `lastKnownState` in the response of the `/list` endpoint.  Haven’t seen that before, but I could check for that.  It might be a rare condition when the bridge is (re-)started while the device is offline.

**Comment by ebaauw** [comment]
In v1.2.7.
